// Generated by scripts/generate-historical-index.ts. Do not edit by hand.
// Statically imports every data/historical/*.json file, so the client
// results page always has data for every ticker without
// anyone needing to remember to add a new import by hand.
import type { HistoricalPrice } from "@/lib/simulate-core";

import AAPL from "./historical/AAPL.json";
import ABBV from "./historical/ABBV.json";
import ABT from "./historical/ABT.json";
import ADBE from "./historical/ADBE.json";
import AEE from "./historical/AEE.json";
import AEP from "./historical/AEP.json";
import AIG from "./historical/AIG.json";
import AMD from "./historical/AMD.json";
import AMGN from "./historical/AMGN.json";
import AMZN from "./historical/AMZN.json";
import AVGO from "./historical/AVGO.json";
import AWK from "./historical/AWK.json";
import AXP from "./historical/AXP.json";
import BA from "./historical/BA.json";
import BAC from "./historical/BAC.json";
import BKNG from "./historical/BKNG.json";
import BKR from "./historical/BKR.json";
import BLK from "./historical/BLK.json";
import BMY from "./historical/BMY.json";
import C from "./historical/C.json";
import CAT from "./historical/CAT.json";
import CI from "./historical/CI.json";
import CL from "./historical/CL.json";
import CLX from "./historical/CLX.json";
import CMG from "./historical/CMG.json";
import CMS from "./historical/CMS.json";
import COF from "./historical/COF.json";
import COP from "./historical/COP.json";
import COST from "./historical/COST.json";
import CRM from "./historical/CRM.json";
import CSCO from "./historical/CSCO.json";
import CSX from "./historical/CSX.json";
import CVS from "./historical/CVS.json";
import CVX from "./historical/CVX.json";
import D from "./historical/D.json";
import DE from "./historical/DE.json";
import DHI from "./historical/DHI.json";
import DUK from "./historical/DUK.json";
import DVN from "./historical/DVN.json";
import EBAY from "./historical/EBAY.json";
import ED from "./historical/ED.json";
import EMR from "./historical/EMR.json";
import EOG from "./historical/EOG.json";
import ES from "./historical/ES.json";
import ETN from "./historical/ETN.json";
import ETR from "./historical/ETR.json";
import EXC from "./historical/EXC.json";
import F from "./historical/F.json";
import FANG from "./historical/FANG.json";
import FDX from "./historical/FDX.json";
import FE from "./historical/FE.json";
import GD from "./historical/GD.json";
import GE from "./historical/GE.json";
import GILD from "./historical/GILD.json";
import GIS from "./historical/GIS.json";
import GOOGL from "./historical/GOOGL.json";
import GS from "./historical/GS.json";
import HAL from "./historical/HAL.json";
import HCA from "./historical/HCA.json";
import HD from "./historical/HD.json";
import HON from "./historical/HON.json";
import HSY from "./historical/HSY.json";
import IBM from "./historical/IBM.json";
import INTC from "./historical/INTC.json";
import INTU from "./historical/INTU.json";
import ISRG from "./historical/ISRG.json";
import JNJ from "./historical/JNJ.json";
import JPM from "./historical/JPM.json";
import KDP from "./historical/KDP.json";
import KMB from "./historical/KMB.json";
import KMI from "./historical/KMI.json";
import KO from "./historical/KO.json";
import KR from "./historical/KR.json";
import LLY from "./historical/LLY.json";
import LMT from "./historical/LMT.json";
import LOW from "./historical/LOW.json";
import MA from "./historical/MA.json";
import MAR from "./historical/MAR.json";
import MCD from "./historical/MCD.json";
import MDLZ from "./historical/MDLZ.json";
import MDT from "./historical/MDT.json";
import MET from "./historical/MET.json";
import META from "./historical/META.json";
import MMM from "./historical/MMM.json";
import MO from "./historical/MO.json";
import MPC from "./historical/MPC.json";
import MRK from "./historical/MRK.json";
import MS from "./historical/MS.json";
import MSFT from "./historical/MSFT.json";
import NEE from "./historical/NEE.json";
import NKE from "./historical/NKE.json";
import NOC from "./historical/NOC.json";
import NOW from "./historical/NOW.json";
import NSC from "./historical/NSC.json";
import NVDA from "./historical/NVDA.json";
import ORCL from "./historical/ORCL.json";
import OXY from "./historical/OXY.json";
import PEG from "./historical/PEG.json";
import PEP from "./historical/PEP.json";
import PFE from "./historical/PFE.json";
import PG from "./historical/PG.json";
import PM from "./historical/PM.json";
import PNC from "./historical/PNC.json";
import PPL from "./historical/PPL.json";
import PSX from "./historical/PSX.json";
import PYPL from "./historical/PYPL.json";
import QCOM from "./historical/QCOM.json";
import RCL from "./historical/RCL.json";
import ROST from "./historical/ROST.json";
import RTX from "./historical/RTX.json";
import SBUX from "./historical/SBUX.json";
import SCHW from "./historical/SCHW.json";
import SLB from "./historical/SLB.json";
import SO from "./historical/SO.json";
import SPGI from "./historical/SPGI.json";
import SRE from "./historical/SRE.json";
import STZ from "./historical/STZ.json";
import SYY from "./historical/SYY.json";
import TFC from "./historical/TFC.json";
import TGT from "./historical/TGT.json";
import TJX from "./historical/TJX.json";
import TMO from "./historical/TMO.json";
import TRGP from "./historical/TRGP.json";
import TSLA from "./historical/TSLA.json";
import TXN from "./historical/TXN.json";
import UNH from "./historical/UNH.json";
import UNP from "./historical/UNP.json";
import UPS from "./historical/UPS.json";
import USB from "./historical/USB.json";
import V from "./historical/V.json";
import VLO from "./historical/VLO.json";
import VRTX from "./historical/VRTX.json";
import WEC from "./historical/WEC.json";
import WFC from "./historical/WFC.json";
import WM from "./historical/WM.json";
import WMB from "./historical/WMB.json";
import WMT from "./historical/WMT.json";
import XEL from "./historical/XEL.json";
import XOM from "./historical/XOM.json";
import YUM from "./historical/YUM.json";
import ZTS from "./historical/ZTS.json";

export const HISTORICAL_DATA: Record<string, HistoricalPrice[]> = {
  AAPL: AAPL,
  ABBV: ABBV,
  ABT: ABT,
  ADBE: ADBE,
  AEE: AEE,
  AEP: AEP,
  AIG: AIG,
  AMD: AMD,
  AMGN: AMGN,
  AMZN: AMZN,
  AVGO: AVGO,
  AWK: AWK,
  AXP: AXP,
  BA: BA,
  BAC: BAC,
  BKNG: BKNG,
  BKR: BKR,
  BLK: BLK,
  BMY: BMY,
  C: C,
  CAT: CAT,
  CI: CI,
  CL: CL,
  CLX: CLX,
  CMG: CMG,
  CMS: CMS,
  COF: COF,
  COP: COP,
  COST: COST,
  CRM: CRM,
  CSCO: CSCO,
  CSX: CSX,
  CVS: CVS,
  CVX: CVX,
  D: D,
  DE: DE,
  DHI: DHI,
  DUK: DUK,
  DVN: DVN,
  EBAY: EBAY,
  ED: ED,
  EMR: EMR,
  EOG: EOG,
  ES: ES,
  ETN: ETN,
  ETR: ETR,
  EXC: EXC,
  F: F,
  FANG: FANG,
  FDX: FDX,
  FE: FE,
  GD: GD,
  GE: GE,
  GILD: GILD,
  GIS: GIS,
  GOOGL: GOOGL,
  GS: GS,
  HAL: HAL,
  HCA: HCA,
  HD: HD,
  HON: HON,
  HSY: HSY,
  IBM: IBM,
  INTC: INTC,
  INTU: INTU,
  ISRG: ISRG,
  JNJ: JNJ,
  JPM: JPM,
  KDP: KDP,
  KMB: KMB,
  KMI: KMI,
  KO: KO,
  KR: KR,
  LLY: LLY,
  LMT: LMT,
  LOW: LOW,
  MA: MA,
  MAR: MAR,
  MCD: MCD,
  MDLZ: MDLZ,
  MDT: MDT,
  MET: MET,
  META: META,
  MMM: MMM,
  MO: MO,
  MPC: MPC,
  MRK: MRK,
  MS: MS,
  MSFT: MSFT,
  NEE: NEE,
  NKE: NKE,
  NOC: NOC,
  NOW: NOW,
  NSC: NSC,
  NVDA: NVDA,
  ORCL: ORCL,
  OXY: OXY,
  PEG: PEG,
  PEP: PEP,
  PFE: PFE,
  PG: PG,
  PM: PM,
  PNC: PNC,
  PPL: PPL,
  PSX: PSX,
  PYPL: PYPL,
  QCOM: QCOM,
  RCL: RCL,
  ROST: ROST,
  RTX: RTX,
  SBUX: SBUX,
  SCHW: SCHW,
  SLB: SLB,
  SO: SO,
  SPGI: SPGI,
  SRE: SRE,
  STZ: STZ,
  SYY: SYY,
  TFC: TFC,
  TGT: TGT,
  TJX: TJX,
  TMO: TMO,
  TRGP: TRGP,
  TSLA: TSLA,
  TXN: TXN,
  UNH: UNH,
  UNP: UNP,
  UPS: UPS,
  USB: USB,
  V: V,
  VLO: VLO,
  VRTX: VRTX,
  WEC: WEC,
  WFC: WFC,
  WM: WM,
  WMB: WMB,
  WMT: WMT,
  XEL: XEL,
  XOM: XOM,
  YUM: YUM,
  ZTS: ZTS,
};
