// Generated by scripts/generate-historical-index.ts. Do not edit by hand.
// Statically imports every data/historical/{year}/*.json file, so the client
// results page always has data for every year/ticker combination without
// anyone needing to remember to add a new import by hand.
import type { HistoricalPrice } from "@/lib/simulate-core";
import type { DraftPick } from "@/lib/types";

import AAPL_2019 from "./historical/2019/AAPL.json";
import ABBV_2019 from "./historical/2019/ABBV.json";
import ABT_2019 from "./historical/2019/ABT.json";
import ADBE_2019 from "./historical/2019/ADBE.json";
import AEE_2019 from "./historical/2019/AEE.json";
import AIG_2019 from "./historical/2019/AIG.json";
import AMGN_2019 from "./historical/2019/AMGN.json";
import AMZN_2019 from "./historical/2019/AMZN.json";
import AVGO_2019 from "./historical/2019/AVGO.json";
import AWK_2019 from "./historical/2019/AWK.json";
import AXP_2019 from "./historical/2019/AXP.json";
import BA_2019 from "./historical/2019/BA.json";
import BKR_2019 from "./historical/2019/BKR.json";
import BLK_2019 from "./historical/2019/BLK.json";
import BMY_2019 from "./historical/2019/BMY.json";
import C_2019 from "./historical/2019/C.json";
import CI_2019 from "./historical/2019/CI.json";
import CL_2019 from "./historical/2019/CL.json";
import CLX_2019 from "./historical/2019/CLX.json";
import CMG_2019 from "./historical/2019/CMG.json";
import CMS_2019 from "./historical/2019/CMS.json";
import COF_2019 from "./historical/2019/COF.json";
import COP_2019 from "./historical/2019/COP.json";
import COST_2019 from "./historical/2019/COST.json";
import CRM_2019 from "./historical/2019/CRM.json";
import CSX_2019 from "./historical/2019/CSX.json";
import CVX_2019 from "./historical/2019/CVX.json";
import DE_2019 from "./historical/2019/DE.json";
import DUK_2019 from "./historical/2019/DUK.json";
import DVN_2019 from "./historical/2019/DVN.json";
import EBAY_2019 from "./historical/2019/EBAY.json";
import ED_2019 from "./historical/2019/ED.json";
import EMR_2019 from "./historical/2019/EMR.json";
import ES_2019 from "./historical/2019/ES.json";
import ETN_2019 from "./historical/2019/ETN.json";
import ETR_2019 from "./historical/2019/ETR.json";
import EXC_2019 from "./historical/2019/EXC.json";
import F_2019 from "./historical/2019/F.json";
import FDX_2019 from "./historical/2019/FDX.json";
import GE_2019 from "./historical/2019/GE.json";
import GILD_2019 from "./historical/2019/GILD.json";
import GM_2019 from "./historical/2019/GM.json";
import GOOGL_2019 from "./historical/2019/GOOGL.json";
import GS_2019 from "./historical/2019/GS.json";
import HCA_2019 from "./historical/2019/HCA.json";
import HD_2019 from "./historical/2019/HD.json";
import HSY_2019 from "./historical/2019/HSY.json";
import IBM_2019 from "./historical/2019/IBM.json";
import INTC_2019 from "./historical/2019/INTC.json";
import INTU_2019 from "./historical/2019/INTU.json";
import ISRG_2019 from "./historical/2019/ISRG.json";
import JNJ_2019 from "./historical/2019/JNJ.json";
import JPM_2019 from "./historical/2019/JPM.json";
import KDP_2019 from "./historical/2019/KDP.json";
import KMI_2019 from "./historical/2019/KMI.json";
import KO_2019 from "./historical/2019/KO.json";
import KR_2019 from "./historical/2019/KR.json";
import LLY_2019 from "./historical/2019/LLY.json";
import LMT_2019 from "./historical/2019/LMT.json";
import LOW_2019 from "./historical/2019/LOW.json";
import MA_2019 from "./historical/2019/MA.json";
import MAR_2019 from "./historical/2019/MAR.json";
import MCD_2019 from "./historical/2019/MCD.json";
import MDLZ_2019 from "./historical/2019/MDLZ.json";
import MDT_2019 from "./historical/2019/MDT.json";
import MET_2019 from "./historical/2019/MET.json";
import META_2019 from "./historical/2019/META.json";
import MMM_2019 from "./historical/2019/MMM.json";
import MO_2019 from "./historical/2019/MO.json";
import MPC_2019 from "./historical/2019/MPC.json";
import MRK_2019 from "./historical/2019/MRK.json";
import MS_2019 from "./historical/2019/MS.json";
import MSFT_2019 from "./historical/2019/MSFT.json";
import NEE_2019 from "./historical/2019/NEE.json";
import NKE_2019 from "./historical/2019/NKE.json";
import NOW_2019 from "./historical/2019/NOW.json";
import NSC_2019 from "./historical/2019/NSC.json";
import NVDA_2019 from "./historical/2019/NVDA.json";
import ORCL_2019 from "./historical/2019/ORCL.json";
import OXY_2019 from "./historical/2019/OXY.json";
import PEG_2019 from "./historical/2019/PEG.json";
import PEP_2019 from "./historical/2019/PEP.json";
import PFE_2019 from "./historical/2019/PFE.json";
import PM_2019 from "./historical/2019/PM.json";
import PNC_2019 from "./historical/2019/PNC.json";
import PSX_2019 from "./historical/2019/PSX.json";
import PYPL_2019 from "./historical/2019/PYPL.json";
import QCOM_2019 from "./historical/2019/QCOM.json";
import RCL_2019 from "./historical/2019/RCL.json";
import ROST_2019 from "./historical/2019/ROST.json";
import RTX_2019 from "./historical/2019/RTX.json";
import SBUX_2019 from "./historical/2019/SBUX.json";
import SCHW_2019 from "./historical/2019/SCHW.json";
import SO_2019 from "./historical/2019/SO.json";
import SRE_2019 from "./historical/2019/SRE.json";
import STZ_2019 from "./historical/2019/STZ.json";
import SYY_2019 from "./historical/2019/SYY.json";
import TFC_2019 from "./historical/2019/TFC.json";
import TGT_2019 from "./historical/2019/TGT.json";
import TMO_2019 from "./historical/2019/TMO.json";
import TRGP_2019 from "./historical/2019/TRGP.json";
import TSLA_2019 from "./historical/2019/TSLA.json";
import TXN_2019 from "./historical/2019/TXN.json";
import UNP_2019 from "./historical/2019/UNP.json";
import UPS_2019 from "./historical/2019/UPS.json";
import V_2019 from "./historical/2019/V.json";
import VLO_2019 from "./historical/2019/VLO.json";
import VRTX_2019 from "./historical/2019/VRTX.json";
import WEC_2019 from "./historical/2019/WEC.json";
import WM_2019 from "./historical/2019/WM.json";
import WMB_2019 from "./historical/2019/WMB.json";
import WMT_2019 from "./historical/2019/WMT.json";
import XEL_2019 from "./historical/2019/XEL.json";
import XOM_2019 from "./historical/2019/XOM.json";
import YUM_2019 from "./historical/2019/YUM.json";
import ZTS_2019 from "./historical/2019/ZTS.json";
import AAPL_2020 from "./historical/2020/AAPL.json";
import ABBV_2020 from "./historical/2020/ABBV.json";
import ADBE_2020 from "./historical/2020/ADBE.json";
import AEE_2020 from "./historical/2020/AEE.json";
import AEP_2020 from "./historical/2020/AEP.json";
import AMD_2020 from "./historical/2020/AMD.json";
import AMGN_2020 from "./historical/2020/AMGN.json";
import AMZN_2020 from "./historical/2020/AMZN.json";
import AWK_2020 from "./historical/2020/AWK.json";
import BA_2020 from "./historical/2020/BA.json";
import BAC_2020 from "./historical/2020/BAC.json";
import BKNG_2020 from "./historical/2020/BKNG.json";
import BKR_2020 from "./historical/2020/BKR.json";
import BLK_2020 from "./historical/2020/BLK.json";
import BMY_2020 from "./historical/2020/BMY.json";
import C_2020 from "./historical/2020/C.json";
import CAT_2020 from "./historical/2020/CAT.json";
import CI_2020 from "./historical/2020/CI.json";
import CL_2020 from "./historical/2020/CL.json";
import CMG_2020 from "./historical/2020/CMG.json";
import CMS_2020 from "./historical/2020/CMS.json";
import COF_2020 from "./historical/2020/COF.json";
import COP_2020 from "./historical/2020/COP.json";
import COST_2020 from "./historical/2020/COST.json";
import CSCO_2020 from "./historical/2020/CSCO.json";
import CSX_2020 from "./historical/2020/CSX.json";
import CVS_2020 from "./historical/2020/CVS.json";
import CVX_2020 from "./historical/2020/CVX.json";
import D_2020 from "./historical/2020/D.json";
import DHI_2020 from "./historical/2020/DHI.json";
import DUK_2020 from "./historical/2020/DUK.json";
import DVN_2020 from "./historical/2020/DVN.json";
import EBAY_2020 from "./historical/2020/EBAY.json";
import ED_2020 from "./historical/2020/ED.json";
import EMR_2020 from "./historical/2020/EMR.json";
import EOG_2020 from "./historical/2020/EOG.json";
import ES_2020 from "./historical/2020/ES.json";
import ETN_2020 from "./historical/2020/ETN.json";
import ETR_2020 from "./historical/2020/ETR.json";
import EXC_2020 from "./historical/2020/EXC.json";
import F_2020 from "./historical/2020/F.json";
import FANG_2020 from "./historical/2020/FANG.json";
import FDX_2020 from "./historical/2020/FDX.json";
import FE_2020 from "./historical/2020/FE.json";
import GD_2020 from "./historical/2020/GD.json";
import GILD_2020 from "./historical/2020/GILD.json";
import GIS_2020 from "./historical/2020/GIS.json";
import GM_2020 from "./historical/2020/GM.json";
import GOOGL_2020 from "./historical/2020/GOOGL.json";
import GS_2020 from "./historical/2020/GS.json";
import HAL_2020 from "./historical/2020/HAL.json";
import HD_2020 from "./historical/2020/HD.json";
import HON_2020 from "./historical/2020/HON.json";
import HSY_2020 from "./historical/2020/HSY.json";
import IBM_2020 from "./historical/2020/IBM.json";
import INTC_2020 from "./historical/2020/INTC.json";
import ISRG_2020 from "./historical/2020/ISRG.json";
import JNJ_2020 from "./historical/2020/JNJ.json";
import JPM_2020 from "./historical/2020/JPM.json";
import KDP_2020 from "./historical/2020/KDP.json";
import KMB_2020 from "./historical/2020/KMB.json";
import KO_2020 from "./historical/2020/KO.json";
import LLY_2020 from "./historical/2020/LLY.json";
import LMT_2020 from "./historical/2020/LMT.json";
import LOW_2020 from "./historical/2020/LOW.json";
import MA_2020 from "./historical/2020/MA.json";
import MAR_2020 from "./historical/2020/MAR.json";
import MDLZ_2020 from "./historical/2020/MDLZ.json";
import MDT_2020 from "./historical/2020/MDT.json";
import MET_2020 from "./historical/2020/MET.json";
import META_2020 from "./historical/2020/META.json";
import MMM_2020 from "./historical/2020/MMM.json";
import MPC_2020 from "./historical/2020/MPC.json";
import MRK_2020 from "./historical/2020/MRK.json";
import MS_2020 from "./historical/2020/MS.json";
import MSFT_2020 from "./historical/2020/MSFT.json";
import NOC_2020 from "./historical/2020/NOC.json";
import NOW_2020 from "./historical/2020/NOW.json";
import NSC_2020 from "./historical/2020/NSC.json";
import NVDA_2020 from "./historical/2020/NVDA.json";
import OXY_2020 from "./historical/2020/OXY.json";
import PEP_2020 from "./historical/2020/PEP.json";
import PFE_2020 from "./historical/2020/PFE.json";
import PG_2020 from "./historical/2020/PG.json";
import PNC_2020 from "./historical/2020/PNC.json";
import PPL_2020 from "./historical/2020/PPL.json";
import PSX_2020 from "./historical/2020/PSX.json";
import PYPL_2020 from "./historical/2020/PYPL.json";
import QCOM_2020 from "./historical/2020/QCOM.json";
import ROST_2020 from "./historical/2020/ROST.json";
import RTX_2020 from "./historical/2020/RTX.json";
import SBUX_2020 from "./historical/2020/SBUX.json";
import SLB_2020 from "./historical/2020/SLB.json";
import SO_2020 from "./historical/2020/SO.json";
import SPGI_2020 from "./historical/2020/SPGI.json";
import SRE_2020 from "./historical/2020/SRE.json";
import STZ_2020 from "./historical/2020/STZ.json";
import SYY_2020 from "./historical/2020/SYY.json";
import TFC_2020 from "./historical/2020/TFC.json";
import TGT_2020 from "./historical/2020/TGT.json";
import TJX_2020 from "./historical/2020/TJX.json";
import TMO_2020 from "./historical/2020/TMO.json";
import TRGP_2020 from "./historical/2020/TRGP.json";
import TSLA_2020 from "./historical/2020/TSLA.json";
import TXN_2020 from "./historical/2020/TXN.json";
import UNH_2020 from "./historical/2020/UNH.json";
import UNP_2020 from "./historical/2020/UNP.json";
import UPS_2020 from "./historical/2020/UPS.json";
import USB_2020 from "./historical/2020/USB.json";
import V_2020 from "./historical/2020/V.json";
import VLO_2020 from "./historical/2020/VLO.json";
import VRTX_2020 from "./historical/2020/VRTX.json";
import WFC_2020 from "./historical/2020/WFC.json";
import WMT_2020 from "./historical/2020/WMT.json";
import XEL_2020 from "./historical/2020/XEL.json";
import ZTS_2020 from "./historical/2020/ZTS.json";
import AAPL_2021 from "./historical/2021/AAPL.json";
import ABT_2021 from "./historical/2021/ABT.json";
import ADBE_2021 from "./historical/2021/ADBE.json";
import AEP_2021 from "./historical/2021/AEP.json";
import AIG_2021 from "./historical/2021/AIG.json";
import AMD_2021 from "./historical/2021/AMD.json";
import AMGN_2021 from "./historical/2021/AMGN.json";
import AMZN_2021 from "./historical/2021/AMZN.json";
import AVGO_2021 from "./historical/2021/AVGO.json";
import AWK_2021 from "./historical/2021/AWK.json";
import AXP_2021 from "./historical/2021/AXP.json";
import BA_2021 from "./historical/2021/BA.json";
import BAC_2021 from "./historical/2021/BAC.json";
import BKNG_2021 from "./historical/2021/BKNG.json";
import BKR_2021 from "./historical/2021/BKR.json";
import BMY_2021 from "./historical/2021/BMY.json";
import CAT_2021 from "./historical/2021/CAT.json";
import CL_2021 from "./historical/2021/CL.json";
import CLX_2021 from "./historical/2021/CLX.json";
import CMG_2021 from "./historical/2021/CMG.json";
import CMS_2021 from "./historical/2021/CMS.json";
import COP_2021 from "./historical/2021/COP.json";
import CRM_2021 from "./historical/2021/CRM.json";
import CSCO_2021 from "./historical/2021/CSCO.json";
import CVS_2021 from "./historical/2021/CVS.json";
import CVX_2021 from "./historical/2021/CVX.json";
import D_2021 from "./historical/2021/D.json";
import DE_2021 from "./historical/2021/DE.json";
import DHI_2021 from "./historical/2021/DHI.json";
import DUK_2021 from "./historical/2021/DUK.json";
import DVN_2021 from "./historical/2021/DVN.json";
import EBAY_2021 from "./historical/2021/EBAY.json";
import EMR_2021 from "./historical/2021/EMR.json";
import EOG_2021 from "./historical/2021/EOG.json";
import ES_2021 from "./historical/2021/ES.json";
import ETN_2021 from "./historical/2021/ETN.json";
import ETR_2021 from "./historical/2021/ETR.json";
import EXC_2021 from "./historical/2021/EXC.json";
import FANG_2021 from "./historical/2021/FANG.json";
import FDX_2021 from "./historical/2021/FDX.json";
import FE_2021 from "./historical/2021/FE.json";
import GD_2021 from "./historical/2021/GD.json";
import GE_2021 from "./historical/2021/GE.json";
import GILD_2021 from "./historical/2021/GILD.json";
import GIS_2021 from "./historical/2021/GIS.json";
import GS_2021 from "./historical/2021/GS.json";
import HAL_2021 from "./historical/2021/HAL.json";
import HCA_2021 from "./historical/2021/HCA.json";
import HON_2021 from "./historical/2021/HON.json";
import INTC_2021 from "./historical/2021/INTC.json";
import INTU_2021 from "./historical/2021/INTU.json";
import JNJ_2021 from "./historical/2021/JNJ.json";
import JPM_2021 from "./historical/2021/JPM.json";
import KDP_2021 from "./historical/2021/KDP.json";
import KMB_2021 from "./historical/2021/KMB.json";
import KMI_2021 from "./historical/2021/KMI.json";
import KO_2021 from "./historical/2021/KO.json";
import KR_2021 from "./historical/2021/KR.json";
import LLY_2021 from "./historical/2021/LLY.json";
import LOW_2021 from "./historical/2021/LOW.json";
import MA_2021 from "./historical/2021/MA.json";
import MAR_2021 from "./historical/2021/MAR.json";
import MCD_2021 from "./historical/2021/MCD.json";
import MDLZ_2021 from "./historical/2021/MDLZ.json";
import MDT_2021 from "./historical/2021/MDT.json";
import META_2021 from "./historical/2021/META.json";
import MMM_2021 from "./historical/2021/MMM.json";
import MO_2021 from "./historical/2021/MO.json";
import MPC_2021 from "./historical/2021/MPC.json";
import MS_2021 from "./historical/2021/MS.json";
import NEE_2021 from "./historical/2021/NEE.json";
import NKE_2021 from "./historical/2021/NKE.json";
import NOC_2021 from "./historical/2021/NOC.json";
import NOW_2021 from "./historical/2021/NOW.json";
import NVDA_2021 from "./historical/2021/NVDA.json";
import ORCL_2021 from "./historical/2021/ORCL.json";
import PEG_2021 from "./historical/2021/PEG.json";
import PEP_2021 from "./historical/2021/PEP.json";
import PFE_2021 from "./historical/2021/PFE.json";
import PG_2021 from "./historical/2021/PG.json";
import PM_2021 from "./historical/2021/PM.json";
import PNC_2021 from "./historical/2021/PNC.json";
import PPL_2021 from "./historical/2021/PPL.json";
import PSX_2021 from "./historical/2021/PSX.json";
import PYPL_2021 from "./historical/2021/PYPL.json";
import RCL_2021 from "./historical/2021/RCL.json";
import ROST_2021 from "./historical/2021/ROST.json";
import SBUX_2021 from "./historical/2021/SBUX.json";
import SCHW_2021 from "./historical/2021/SCHW.json";
import SLB_2021 from "./historical/2021/SLB.json";
import SO_2021 from "./historical/2021/SO.json";
import SPGI_2021 from "./historical/2021/SPGI.json";
import SRE_2021 from "./historical/2021/SRE.json";
import STZ_2021 from "./historical/2021/STZ.json";
import TFC_2021 from "./historical/2021/TFC.json";
import TGT_2021 from "./historical/2021/TGT.json";
import TJX_2021 from "./historical/2021/TJX.json";
import TMO_2021 from "./historical/2021/TMO.json";
import TRGP_2021 from "./historical/2021/TRGP.json";
import TXN_2021 from "./historical/2021/TXN.json";
import UNH_2021 from "./historical/2021/UNH.json";
import UNP_2021 from "./historical/2021/UNP.json";
import UPS_2021 from "./historical/2021/UPS.json";
import USB_2021 from "./historical/2021/USB.json";
import V_2021 from "./historical/2021/V.json";
import VRTX_2021 from "./historical/2021/VRTX.json";
import WEC_2021 from "./historical/2021/WEC.json";
import WFC_2021 from "./historical/2021/WFC.json";
import WM_2021 from "./historical/2021/WM.json";
import WMB_2021 from "./historical/2021/WMB.json";
import XOM_2021 from "./historical/2021/XOM.json";
import YUM_2021 from "./historical/2021/YUM.json";
import ZTS_2021 from "./historical/2021/ZTS.json";
import AAPL_2022 from "./historical/2022/AAPL.json";
import ABBV_2022 from "./historical/2022/ABBV.json";
import ABT_2022 from "./historical/2022/ABT.json";
import ADBE_2022 from "./historical/2022/ADBE.json";
import AEE_2022 from "./historical/2022/AEE.json";
import AEP_2022 from "./historical/2022/AEP.json";
import AIG_2022 from "./historical/2022/AIG.json";
import AMD_2022 from "./historical/2022/AMD.json";
import AMGN_2022 from "./historical/2022/AMGN.json";
import AMZN_2022 from "./historical/2022/AMZN.json";
import AVGO_2022 from "./historical/2022/AVGO.json";
import AWK_2022 from "./historical/2022/AWK.json";
import AXP_2022 from "./historical/2022/AXP.json";
import BA_2022 from "./historical/2022/BA.json";
import BAC_2022 from "./historical/2022/BAC.json";
import BKNG_2022 from "./historical/2022/BKNG.json";
import BKR_2022 from "./historical/2022/BKR.json";
import BLK_2022 from "./historical/2022/BLK.json";
import BMY_2022 from "./historical/2022/BMY.json";
import C_2022 from "./historical/2022/C.json";
import CAT_2022 from "./historical/2022/CAT.json";
import CI_2022 from "./historical/2022/CI.json";
import CL_2022 from "./historical/2022/CL.json";
import CLX_2022 from "./historical/2022/CLX.json";
import CMG_2022 from "./historical/2022/CMG.json";
import CMS_2022 from "./historical/2022/CMS.json";
import COF_2022 from "./historical/2022/COF.json";
import COP_2022 from "./historical/2022/COP.json";
import COST_2022 from "./historical/2022/COST.json";
import CRM_2022 from "./historical/2022/CRM.json";
import CSCO_2022 from "./historical/2022/CSCO.json";
import CSX_2022 from "./historical/2022/CSX.json";
import CVS_2022 from "./historical/2022/CVS.json";
import CVX_2022 from "./historical/2022/CVX.json";
import D_2022 from "./historical/2022/D.json";
import DE_2022 from "./historical/2022/DE.json";
import DHI_2022 from "./historical/2022/DHI.json";
import DUK_2022 from "./historical/2022/DUK.json";
import DVN_2022 from "./historical/2022/DVN.json";
import EBAY_2022 from "./historical/2022/EBAY.json";
import ED_2022 from "./historical/2022/ED.json";
import EMR_2022 from "./historical/2022/EMR.json";
import EOG_2022 from "./historical/2022/EOG.json";
import ES_2022 from "./historical/2022/ES.json";
import ETN_2022 from "./historical/2022/ETN.json";
import ETR_2022 from "./historical/2022/ETR.json";
import EXC_2022 from "./historical/2022/EXC.json";
import F_2022 from "./historical/2022/F.json";
import FANG_2022 from "./historical/2022/FANG.json";
import FDX_2022 from "./historical/2022/FDX.json";
import FE_2022 from "./historical/2022/FE.json";
import GD_2022 from "./historical/2022/GD.json";
import GE_2022 from "./historical/2022/GE.json";
import GILD_2022 from "./historical/2022/GILD.json";
import GIS_2022 from "./historical/2022/GIS.json";
import GM_2022 from "./historical/2022/GM.json";
import GOOGL_2022 from "./historical/2022/GOOGL.json";
import GS_2022 from "./historical/2022/GS.json";
import HAL_2022 from "./historical/2022/HAL.json";
import HCA_2022 from "./historical/2022/HCA.json";
import HD_2022 from "./historical/2022/HD.json";
import HON_2022 from "./historical/2022/HON.json";
import HSY_2022 from "./historical/2022/HSY.json";
import IBM_2022 from "./historical/2022/IBM.json";
import INTC_2022 from "./historical/2022/INTC.json";
import INTU_2022 from "./historical/2022/INTU.json";
import ISRG_2022 from "./historical/2022/ISRG.json";
import JNJ_2022 from "./historical/2022/JNJ.json";
import JPM_2022 from "./historical/2022/JPM.json";
import KDP_2022 from "./historical/2022/KDP.json";
import KMB_2022 from "./historical/2022/KMB.json";
import KMI_2022 from "./historical/2022/KMI.json";
import KO_2022 from "./historical/2022/KO.json";
import KR_2022 from "./historical/2022/KR.json";
import LLY_2022 from "./historical/2022/LLY.json";
import LMT_2022 from "./historical/2022/LMT.json";
import LOW_2022 from "./historical/2022/LOW.json";
import MA_2022 from "./historical/2022/MA.json";
import MAR_2022 from "./historical/2022/MAR.json";
import MCD_2022 from "./historical/2022/MCD.json";
import MDLZ_2022 from "./historical/2022/MDLZ.json";
import MDT_2022 from "./historical/2022/MDT.json";
import MET_2022 from "./historical/2022/MET.json";
import META_2022 from "./historical/2022/META.json";
import MMM_2022 from "./historical/2022/MMM.json";
import MO_2022 from "./historical/2022/MO.json";
import MPC_2022 from "./historical/2022/MPC.json";
import MRK_2022 from "./historical/2022/MRK.json";
import MS_2022 from "./historical/2022/MS.json";
import MSFT_2022 from "./historical/2022/MSFT.json";
import NEE_2022 from "./historical/2022/NEE.json";
import NKE_2022 from "./historical/2022/NKE.json";
import NOC_2022 from "./historical/2022/NOC.json";
import NOW_2022 from "./historical/2022/NOW.json";
import NSC_2022 from "./historical/2022/NSC.json";
import NVDA_2022 from "./historical/2022/NVDA.json";
import ORCL_2022 from "./historical/2022/ORCL.json";
import OXY_2022 from "./historical/2022/OXY.json";
import PEG_2022 from "./historical/2022/PEG.json";
import PEP_2022 from "./historical/2022/PEP.json";
import PFE_2022 from "./historical/2022/PFE.json";
import PG_2022 from "./historical/2022/PG.json";
import PM_2022 from "./historical/2022/PM.json";
import PNC_2022 from "./historical/2022/PNC.json";
import PPL_2022 from "./historical/2022/PPL.json";
import PSX_2022 from "./historical/2022/PSX.json";
import PYPL_2022 from "./historical/2022/PYPL.json";
import QCOM_2022 from "./historical/2022/QCOM.json";
import RCL_2022 from "./historical/2022/RCL.json";
import ROST_2022 from "./historical/2022/ROST.json";
import RTX_2022 from "./historical/2022/RTX.json";
import SBUX_2022 from "./historical/2022/SBUX.json";
import SCHW_2022 from "./historical/2022/SCHW.json";
import SLB_2022 from "./historical/2022/SLB.json";
import SO_2022 from "./historical/2022/SO.json";
import SPGI_2022 from "./historical/2022/SPGI.json";
import SRE_2022 from "./historical/2022/SRE.json";
import STZ_2022 from "./historical/2022/STZ.json";
import SYY_2022 from "./historical/2022/SYY.json";
import TFC_2022 from "./historical/2022/TFC.json";
import TGT_2022 from "./historical/2022/TGT.json";
import TJX_2022 from "./historical/2022/TJX.json";
import TMO_2022 from "./historical/2022/TMO.json";
import TRGP_2022 from "./historical/2022/TRGP.json";
import TSLA_2022 from "./historical/2022/TSLA.json";
import TXN_2022 from "./historical/2022/TXN.json";
import UNH_2022 from "./historical/2022/UNH.json";
import UNP_2022 from "./historical/2022/UNP.json";
import UPS_2022 from "./historical/2022/UPS.json";
import USB_2022 from "./historical/2022/USB.json";
import V_2022 from "./historical/2022/V.json";
import VLO_2022 from "./historical/2022/VLO.json";
import VRTX_2022 from "./historical/2022/VRTX.json";
import WEC_2022 from "./historical/2022/WEC.json";
import WFC_2022 from "./historical/2022/WFC.json";
import WM_2022 from "./historical/2022/WM.json";
import WMB_2022 from "./historical/2022/WMB.json";
import WMT_2022 from "./historical/2022/WMT.json";
import XEL_2022 from "./historical/2022/XEL.json";
import XOM_2022 from "./historical/2022/XOM.json";
import YUM_2022 from "./historical/2022/YUM.json";
import ZTS_2022 from "./historical/2022/ZTS.json";

export const HISTORICAL_DATA: Partial<Record<DraftPick["year"], Partial<Record<string, HistoricalPrice[]>>>> = {
  2019: {
    AAPL: AAPL_2019,
    ABBV: ABBV_2019,
    ABT: ABT_2019,
    ADBE: ADBE_2019,
    AEE: AEE_2019,
    AIG: AIG_2019,
    AMGN: AMGN_2019,
    AMZN: AMZN_2019,
    AVGO: AVGO_2019,
    AWK: AWK_2019,
    AXP: AXP_2019,
    BA: BA_2019,
    BKR: BKR_2019,
    BLK: BLK_2019,
    BMY: BMY_2019,
    C: C_2019,
    CI: CI_2019,
    CL: CL_2019,
    CLX: CLX_2019,
    CMG: CMG_2019,
    CMS: CMS_2019,
    COF: COF_2019,
    COP: COP_2019,
    COST: COST_2019,
    CRM: CRM_2019,
    CSX: CSX_2019,
    CVX: CVX_2019,
    DE: DE_2019,
    DUK: DUK_2019,
    DVN: DVN_2019,
    EBAY: EBAY_2019,
    ED: ED_2019,
    EMR: EMR_2019,
    ES: ES_2019,
    ETN: ETN_2019,
    ETR: ETR_2019,
    EXC: EXC_2019,
    F: F_2019,
    FDX: FDX_2019,
    GE: GE_2019,
    GILD: GILD_2019,
    GM: GM_2019,
    GOOGL: GOOGL_2019,
    GS: GS_2019,
    HCA: HCA_2019,
    HD: HD_2019,
    HSY: HSY_2019,
    IBM: IBM_2019,
    INTC: INTC_2019,
    INTU: INTU_2019,
    ISRG: ISRG_2019,
    JNJ: JNJ_2019,
    JPM: JPM_2019,
    KDP: KDP_2019,
    KMI: KMI_2019,
    KO: KO_2019,
    KR: KR_2019,
    LLY: LLY_2019,
    LMT: LMT_2019,
    LOW: LOW_2019,
    MA: MA_2019,
    MAR: MAR_2019,
    MCD: MCD_2019,
    MDLZ: MDLZ_2019,
    MDT: MDT_2019,
    MET: MET_2019,
    META: META_2019,
    MMM: MMM_2019,
    MO: MO_2019,
    MPC: MPC_2019,
    MRK: MRK_2019,
    MS: MS_2019,
    MSFT: MSFT_2019,
    NEE: NEE_2019,
    NKE: NKE_2019,
    NOW: NOW_2019,
    NSC: NSC_2019,
    NVDA: NVDA_2019,
    ORCL: ORCL_2019,
    OXY: OXY_2019,
    PEG: PEG_2019,
    PEP: PEP_2019,
    PFE: PFE_2019,
    PM: PM_2019,
    PNC: PNC_2019,
    PSX: PSX_2019,
    PYPL: PYPL_2019,
    QCOM: QCOM_2019,
    RCL: RCL_2019,
    ROST: ROST_2019,
    RTX: RTX_2019,
    SBUX: SBUX_2019,
    SCHW: SCHW_2019,
    SO: SO_2019,
    SRE: SRE_2019,
    STZ: STZ_2019,
    SYY: SYY_2019,
    TFC: TFC_2019,
    TGT: TGT_2019,
    TMO: TMO_2019,
    TRGP: TRGP_2019,
    TSLA: TSLA_2019,
    TXN: TXN_2019,
    UNP: UNP_2019,
    UPS: UPS_2019,
    V: V_2019,
    VLO: VLO_2019,
    VRTX: VRTX_2019,
    WEC: WEC_2019,
    WM: WM_2019,
    WMB: WMB_2019,
    WMT: WMT_2019,
    XEL: XEL_2019,
    XOM: XOM_2019,
    YUM: YUM_2019,
    ZTS: ZTS_2019,
  },
  2020: {
    AAPL: AAPL_2020,
    ABBV: ABBV_2020,
    ADBE: ADBE_2020,
    AEE: AEE_2020,
    AEP: AEP_2020,
    AMD: AMD_2020,
    AMGN: AMGN_2020,
    AMZN: AMZN_2020,
    AWK: AWK_2020,
    BA: BA_2020,
    BAC: BAC_2020,
    BKNG: BKNG_2020,
    BKR: BKR_2020,
    BLK: BLK_2020,
    BMY: BMY_2020,
    C: C_2020,
    CAT: CAT_2020,
    CI: CI_2020,
    CL: CL_2020,
    CMG: CMG_2020,
    CMS: CMS_2020,
    COF: COF_2020,
    COP: COP_2020,
    COST: COST_2020,
    CSCO: CSCO_2020,
    CSX: CSX_2020,
    CVS: CVS_2020,
    CVX: CVX_2020,
    D: D_2020,
    DHI: DHI_2020,
    DUK: DUK_2020,
    DVN: DVN_2020,
    EBAY: EBAY_2020,
    ED: ED_2020,
    EMR: EMR_2020,
    EOG: EOG_2020,
    ES: ES_2020,
    ETN: ETN_2020,
    ETR: ETR_2020,
    EXC: EXC_2020,
    F: F_2020,
    FANG: FANG_2020,
    FDX: FDX_2020,
    FE: FE_2020,
    GD: GD_2020,
    GILD: GILD_2020,
    GIS: GIS_2020,
    GM: GM_2020,
    GOOGL: GOOGL_2020,
    GS: GS_2020,
    HAL: HAL_2020,
    HD: HD_2020,
    HON: HON_2020,
    HSY: HSY_2020,
    IBM: IBM_2020,
    INTC: INTC_2020,
    ISRG: ISRG_2020,
    JNJ: JNJ_2020,
    JPM: JPM_2020,
    KDP: KDP_2020,
    KMB: KMB_2020,
    KO: KO_2020,
    LLY: LLY_2020,
    LMT: LMT_2020,
    LOW: LOW_2020,
    MA: MA_2020,
    MAR: MAR_2020,
    MDLZ: MDLZ_2020,
    MDT: MDT_2020,
    MET: MET_2020,
    META: META_2020,
    MMM: MMM_2020,
    MPC: MPC_2020,
    MRK: MRK_2020,
    MS: MS_2020,
    MSFT: MSFT_2020,
    NOC: NOC_2020,
    NOW: NOW_2020,
    NSC: NSC_2020,
    NVDA: NVDA_2020,
    OXY: OXY_2020,
    PEP: PEP_2020,
    PFE: PFE_2020,
    PG: PG_2020,
    PNC: PNC_2020,
    PPL: PPL_2020,
    PSX: PSX_2020,
    PYPL: PYPL_2020,
    QCOM: QCOM_2020,
    ROST: ROST_2020,
    RTX: RTX_2020,
    SBUX: SBUX_2020,
    SLB: SLB_2020,
    SO: SO_2020,
    SPGI: SPGI_2020,
    SRE: SRE_2020,
    STZ: STZ_2020,
    SYY: SYY_2020,
    TFC: TFC_2020,
    TGT: TGT_2020,
    TJX: TJX_2020,
    TMO: TMO_2020,
    TRGP: TRGP_2020,
    TSLA: TSLA_2020,
    TXN: TXN_2020,
    UNH: UNH_2020,
    UNP: UNP_2020,
    UPS: UPS_2020,
    USB: USB_2020,
    V: V_2020,
    VLO: VLO_2020,
    VRTX: VRTX_2020,
    WFC: WFC_2020,
    WMT: WMT_2020,
    XEL: XEL_2020,
    ZTS: ZTS_2020,
  },
  2021: {
    AAPL: AAPL_2021,
    ABT: ABT_2021,
    ADBE: ADBE_2021,
    AEP: AEP_2021,
    AIG: AIG_2021,
    AMD: AMD_2021,
    AMGN: AMGN_2021,
    AMZN: AMZN_2021,
    AVGO: AVGO_2021,
    AWK: AWK_2021,
    AXP: AXP_2021,
    BA: BA_2021,
    BAC: BAC_2021,
    BKNG: BKNG_2021,
    BKR: BKR_2021,
    BMY: BMY_2021,
    CAT: CAT_2021,
    CL: CL_2021,
    CLX: CLX_2021,
    CMG: CMG_2021,
    CMS: CMS_2021,
    COP: COP_2021,
    CRM: CRM_2021,
    CSCO: CSCO_2021,
    CVS: CVS_2021,
    CVX: CVX_2021,
    D: D_2021,
    DE: DE_2021,
    DHI: DHI_2021,
    DUK: DUK_2021,
    DVN: DVN_2021,
    EBAY: EBAY_2021,
    EMR: EMR_2021,
    EOG: EOG_2021,
    ES: ES_2021,
    ETN: ETN_2021,
    ETR: ETR_2021,
    EXC: EXC_2021,
    FANG: FANG_2021,
    FDX: FDX_2021,
    FE: FE_2021,
    GD: GD_2021,
    GE: GE_2021,
    GILD: GILD_2021,
    GIS: GIS_2021,
    GS: GS_2021,
    HAL: HAL_2021,
    HCA: HCA_2021,
    HON: HON_2021,
    INTC: INTC_2021,
    INTU: INTU_2021,
    JNJ: JNJ_2021,
    JPM: JPM_2021,
    KDP: KDP_2021,
    KMB: KMB_2021,
    KMI: KMI_2021,
    KO: KO_2021,
    KR: KR_2021,
    LLY: LLY_2021,
    LOW: LOW_2021,
    MA: MA_2021,
    MAR: MAR_2021,
    MCD: MCD_2021,
    MDLZ: MDLZ_2021,
    MDT: MDT_2021,
    META: META_2021,
    MMM: MMM_2021,
    MO: MO_2021,
    MPC: MPC_2021,
    MS: MS_2021,
    NEE: NEE_2021,
    NKE: NKE_2021,
    NOC: NOC_2021,
    NOW: NOW_2021,
    NVDA: NVDA_2021,
    ORCL: ORCL_2021,
    PEG: PEG_2021,
    PEP: PEP_2021,
    PFE: PFE_2021,
    PG: PG_2021,
    PM: PM_2021,
    PNC: PNC_2021,
    PPL: PPL_2021,
    PSX: PSX_2021,
    PYPL: PYPL_2021,
    RCL: RCL_2021,
    ROST: ROST_2021,
    SBUX: SBUX_2021,
    SCHW: SCHW_2021,
    SLB: SLB_2021,
    SO: SO_2021,
    SPGI: SPGI_2021,
    SRE: SRE_2021,
    STZ: STZ_2021,
    TFC: TFC_2021,
    TGT: TGT_2021,
    TJX: TJX_2021,
    TMO: TMO_2021,
    TRGP: TRGP_2021,
    TXN: TXN_2021,
    UNH: UNH_2021,
    UNP: UNP_2021,
    UPS: UPS_2021,
    USB: USB_2021,
    V: V_2021,
    VRTX: VRTX_2021,
    WEC: WEC_2021,
    WFC: WFC_2021,
    WM: WM_2021,
    WMB: WMB_2021,
    XOM: XOM_2021,
    YUM: YUM_2021,
    ZTS: ZTS_2021,
  },
  2022: {
    AAPL: AAPL_2022,
    ABBV: ABBV_2022,
    ABT: ABT_2022,
    ADBE: ADBE_2022,
    AEE: AEE_2022,
    AEP: AEP_2022,
    AIG: AIG_2022,
    AMD: AMD_2022,
    AMGN: AMGN_2022,
    AMZN: AMZN_2022,
    AVGO: AVGO_2022,
    AWK: AWK_2022,
    AXP: AXP_2022,
    BA: BA_2022,
    BAC: BAC_2022,
    BKNG: BKNG_2022,
    BKR: BKR_2022,
    BLK: BLK_2022,
    BMY: BMY_2022,
    C: C_2022,
    CAT: CAT_2022,
    CI: CI_2022,
    CL: CL_2022,
    CLX: CLX_2022,
    CMG: CMG_2022,
    CMS: CMS_2022,
    COF: COF_2022,
    COP: COP_2022,
    COST: COST_2022,
    CRM: CRM_2022,
    CSCO: CSCO_2022,
    CSX: CSX_2022,
    CVS: CVS_2022,
    CVX: CVX_2022,
    D: D_2022,
    DE: DE_2022,
    DHI: DHI_2022,
    DUK: DUK_2022,
    DVN: DVN_2022,
    EBAY: EBAY_2022,
    ED: ED_2022,
    EMR: EMR_2022,
    EOG: EOG_2022,
    ES: ES_2022,
    ETN: ETN_2022,
    ETR: ETR_2022,
    EXC: EXC_2022,
    F: F_2022,
    FANG: FANG_2022,
    FDX: FDX_2022,
    FE: FE_2022,
    GD: GD_2022,
    GE: GE_2022,
    GILD: GILD_2022,
    GIS: GIS_2022,
    GM: GM_2022,
    GOOGL: GOOGL_2022,
    GS: GS_2022,
    HAL: HAL_2022,
    HCA: HCA_2022,
    HD: HD_2022,
    HON: HON_2022,
    HSY: HSY_2022,
    IBM: IBM_2022,
    INTC: INTC_2022,
    INTU: INTU_2022,
    ISRG: ISRG_2022,
    JNJ: JNJ_2022,
    JPM: JPM_2022,
    KDP: KDP_2022,
    KMB: KMB_2022,
    KMI: KMI_2022,
    KO: KO_2022,
    KR: KR_2022,
    LLY: LLY_2022,
    LMT: LMT_2022,
    LOW: LOW_2022,
    MA: MA_2022,
    MAR: MAR_2022,
    MCD: MCD_2022,
    MDLZ: MDLZ_2022,
    MDT: MDT_2022,
    MET: MET_2022,
    META: META_2022,
    MMM: MMM_2022,
    MO: MO_2022,
    MPC: MPC_2022,
    MRK: MRK_2022,
    MS: MS_2022,
    MSFT: MSFT_2022,
    NEE: NEE_2022,
    NKE: NKE_2022,
    NOC: NOC_2022,
    NOW: NOW_2022,
    NSC: NSC_2022,
    NVDA: NVDA_2022,
    ORCL: ORCL_2022,
    OXY: OXY_2022,
    PEG: PEG_2022,
    PEP: PEP_2022,
    PFE: PFE_2022,
    PG: PG_2022,
    PM: PM_2022,
    PNC: PNC_2022,
    PPL: PPL_2022,
    PSX: PSX_2022,
    PYPL: PYPL_2022,
    QCOM: QCOM_2022,
    RCL: RCL_2022,
    ROST: ROST_2022,
    RTX: RTX_2022,
    SBUX: SBUX_2022,
    SCHW: SCHW_2022,
    SLB: SLB_2022,
    SO: SO_2022,
    SPGI: SPGI_2022,
    SRE: SRE_2022,
    STZ: STZ_2022,
    SYY: SYY_2022,
    TFC: TFC_2022,
    TGT: TGT_2022,
    TJX: TJX_2022,
    TMO: TMO_2022,
    TRGP: TRGP_2022,
    TSLA: TSLA_2022,
    TXN: TXN_2022,
    UNH: UNH_2022,
    UNP: UNP_2022,
    UPS: UPS_2022,
    USB: USB_2022,
    V: V_2022,
    VLO: VLO_2022,
    VRTX: VRTX_2022,
    WEC: WEC_2022,
    WFC: WFC_2022,
    WM: WM_2022,
    WMB: WMB_2022,
    WMT: WMT_2022,
    XEL: XEL_2022,
    XOM: XOM_2022,
    YUM: YUM_2022,
    ZTS: ZTS_2022,
  },
};
