import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const HISTORICAL_DIR = path.resolve(process.cwd(), "data/historical");
const OUTPUT_FILE = path.resolve(process.cwd(), "data/historical-index.ts");

const SUPPORTED_YEARS = [2019, 2020, 2021, 2022] as const;

function main(): void {
  const years = SUPPORTED_YEARS.map(String).filter((year) => {
    return readdirSync(HISTORICAL_DIR).includes(year);
  });

  const imports = years
    .flatMap((year) => {
      const tickers = readdirSync(path.join(HISTORICAL_DIR, year))
        .filter((file) => file.endsWith(".json"))
        .map((file) => file.replace(/\.json$/, ""))
        .sort();

      return tickers.map((ticker) => `import ${ticker}_${year} from "./historical/${year}/${ticker}.json";`);
    })
    .join("\n");
  const entries = years
    .map((year) => {
      const tickers = readdirSync(path.join(HISTORICAL_DIR, year))
        .filter((file) => file.endsWith(".json"))
        .map((file) => file.replace(/\.json$/, ""))
        .sort();

      const yearEntries = tickers.map((ticker) => `    ${ticker}: ${ticker}_${year},`).join("\n");
      return `  ${year}: {\n${yearEntries}\n  },`;
    })
    .join("\n");

  const contents = `// Generated by scripts/generate-historical-index.ts. Do not edit by hand.
// Statically imports every data/historical/{year}/*.json file, so the client
// results page always has data for every year/ticker combination without
// anyone needing to remember to add a new import by hand.
import type { HistoricalPrice } from "@/lib/simulate-core";
import type { DraftPick } from "@/lib/types";

${imports}

export const HISTORICAL_DATA: Partial<Record<DraftPick["year"], Partial<Record<string, HistoricalPrice[]>>>> = {
${entries}
};
`;

  writeFileSync(OUTPUT_FILE, contents, "utf8");
  console.log(`Wrote historical data index for ${years.length} years to ${OUTPUT_FILE}`);
}

main();
