import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const HISTORICAL_DIR = path.resolve(process.cwd(), "data/historical");
const OUTPUT_FILE = path.resolve(process.cwd(), "data/historical-index.ts");

function main(): void {
  const tickers = readdirSync(HISTORICAL_DIR)
    .filter((file) => file.endsWith(".json"))
    .map((file) => file.replace(/\.json$/, ""))
    .sort();

  const imports = tickers
    .map((ticker) => `import ${ticker} from "./historical/${ticker}.json";`)
    .join("\n");
  const entries = tickers.map((ticker) => `  ${ticker},`).join("\n");

  const contents = `// Generated by scripts/generate-historical-index.ts. Do not edit by hand.
// Statically imports every data/historical/*.json file, so the client
// results page always has data for every ticker in data/sectors.ts without
// anyone needing to remember to add a new import by hand.
import type { HistoricalPrice } from "@/lib/simulate-core";

${imports}

export const HISTORICAL_DATA: Partial<Record<string, HistoricalPrice[]>> = {
${entries}
};
`;

  writeFileSync(OUTPUT_FILE, contents, "utf8");
  console.log(`Wrote historical data index for ${tickers.length} tickers to ${OUTPUT_FILE}`);
}

main();
