import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type HistoricalPrice = {
  date: string;
  close: number;
};

const HISTORICAL_DIR = path.resolve(process.cwd(), "data/historical");
const OUTPUT_FILE = path.resolve(process.cwd(), "data/starting-prices.ts");

function main(): void {
  const files = readdirSync(HISTORICAL_DIR).filter((file) => file.endsWith(".json"));
  const startingPrices: Record<string, number> = {};

  for (const file of files) {
    const ticker = file.replace(/\.json$/, "");
    const prices = JSON.parse(
      readFileSync(path.join(HISTORICAL_DIR, file), "utf8"),
    ) as HistoricalPrice[];

    startingPrices[ticker] = prices[0].close;
  }

  const entries = Object.keys(startingPrices)
    .sort()
    .map((ticker) => `  ${ticker}: ${startingPrices[ticker]},`)
    .join("\n");

  const contents = `// Generated by scripts/generate-starting-prices.ts. Do not edit by hand.
// Each ticker's closing price on the first trading day of 2022 (2022-01-03),
// used for Informed Mode. Never add ending prices or returns here, since
// that would reveal the 2022 backtest outcome during the draft.
export const STARTING_PRICES: Record<string, number> = {
${entries}
};
`;

  writeFileSync(OUTPUT_FILE, contents, "utf8");
  console.log(`Wrote starting prices for ${files.length} tickers to ${OUTPUT_FILE}`);
}

main();
